#!/usr/bin/env bash
# Demo script — simulates full voc.sh output for recording
# Uses real API data + pre-rendered report (no openclaw needed)

set -euo pipefail

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

ASIN="B099Z93WD9"

# Banner
echo -e "${BLUE}"
echo "  ██╗   ██╗ ██████╗  ██████╗      █████╗ ██╗"
echo "  ██║   ██║██╔═══██╗██╔════╝     ██╔══██╗██║"
echo "  ██║   ██║██║   ██║██║          ███████║██║"
echo "  ╚██╗ ██╔╝██║   ██║██║          ██╔══██║██║"
echo "   ╚████╔╝ ╚██████╔╝╚██████╗     ██║  ██║██║"
echo "    ╚═══╝   ╚═════╝  ╚═════╝     ╚═╝  ╚═╝╚═╝"
echo -e "${NC}"
echo "  Amazon Review Intelligence | Powered by Shulex VOC"
echo "  ─────────────────────────────────────────────────────"
echo ""

echo -e "${GREEN}Analyzing ASIN: ${YELLOW}$ASIN${NC}"
echo -e "  Market: US | Reviews: 8"
echo ""

# Step 1: Fetch (real API call)
echo -e "${BLUE}[1/2] Fetching review data via Shulex VOC API...${NC}"

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMP_DATA=$(mktemp /tmp/voc_demo_XXXXXX.json)
trap "rm -f $TEMP_DATA" EXIT

bash "$SKILL_DIR/fetch.sh" "$ASIN" --limit 8 --market US --output "$TEMP_DATA" 2>&1 | grep -v "^$"

REVIEW_COUNT=$(python3 -c "import json; d=json.load(open('$TEMP_DATA')); print(len(d.get('reviews',[])))" 2>/dev/null || echo "0")
TOTAL_AVAIL=$(python3 -c "import json; print(json.load(open('$TEMP_DATA')).get('meta',{}).get('total_available',0))" 2>/dev/null || echo "10")

echo -e "${GREEN}Retrieved $REVIEW_COUNT reviews (total available: $TOTAL_AVAIL)${NC}"
echo ""

# Step 2: Pre-rendered report
echo -e "${BLUE}[2/2] AI deep analysis...${NC}"
sleep 1

cat <<'REPORT'

╔══════════════════════════════════════════════════════════════╗
║                 VOC AI Analysis Report                       ║
║  ASIN: B099Z93WD9  |  analyzed: 8 reviews                   ║
║  Market: US  |  Generated: 2026-04-19                        ║
╚══════════════════════════════════════════════════════════════╝

📊 Sentiment Distribution
─────────────────────────────────────────
  Positive  ████████░░░░░░░░░░░░  37%
  Neutral   ██░░░░░░░░░░░░░░░░░░  13%
  Negative  ██████████░░░░░░░░░░  50%

🔴 Top 5 Pain Points
═══════════════════════════════════════════════════════════════
1. Charging port moisture glitch (2 mentions)
   "Moisture in charging port — known glitch, a week in and still can't charge"

2. Video stalling and weak connection (2 mentions)
   "It stalls out, pausing videos, really annoying when entertaining a toddler"

3. Limited app store selection (1 mention)
   "The Amazon Silk Browser is terrible, APP store offers nothing"

4. Forced obsolescence by Amazon (1 mention)
   "After 14 years Amazon says no longer supported — who does this?"

🟢 Top 5 Selling Points
═══════════════════════════════════════════════════════════════
1. Great value for money (3 mentions)
   "Budget friendly, provides entertainment on the go"

2. Perfect portable size (2 mentions)
   "Perfect size, light and easy to fit in my purse"

3. Good for reading (2 mentions)
   "When using it to read books, it is fine"

💡 Listing Optimization Suggestions
═══════════════════════════════════════════════════════════════
1. Highlight budget-friendly and portability in title

2. Add charging port care instructions in A+ Content

3. Guide users to sideload popular apps

📌 Summary
─────────────────────────────────────────
  Half the negatives are hardware bugs & ecosystem lock-in,
  but fans love the price-to-value ratio and portability

══════════════════════════════════════════════════════════════
  Generated by VOC AI Skill
  https://github.com/mguozhen/voc-amazon-reviews
══════════════════════════════════════════════════════════════
REPORT

echo ""
echo -e "${GREEN}Analysis complete!${NC}"
echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "  This report analyzed ${YELLOW}8${NC} of ${YELLOW}$TOTAL_AVAIL${NC} available reviews."
echo -e "  For deeper insights, increase your limit:"
echo ""
echo -e "    ${GREEN}voc.sh $ASIN --limit 100${NC}"
echo ""
echo -e "  Need more credits? ${CYAN}https://apps.voc.ai/openapi/billing${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
